export const ui = {
  en: {
    "meta.title": "Tokimura | A Preserved Fragment of Time: A Ryokan in Mikuni, Fukui",
    "meta.description": "Not Kyoto, But Mikuni. A 1928 traditional Japanese house offering preserved fragment for your breath. Experience the unhurried flow of time on the hidden coast of the sea opposite the Pacific Ocean.",
    "hero.title": "Not Kyoto, But Mikuni.",
    "hero.subtitle": "The Japan You Wished Existed.",
    "hero.description": "Far from the lost tranquility of crowded tourist routes, \na proud and authentic everyday life still breathes on the Sea of Japan.",
    "hero.scroll": "Scroll",
    "about.label": "About Tokimura",
    "about.title": "1928: Preserved Fragment for Your Breath.",
    "about.p1": "Built in 1928, this house preserves the traditional Japanese way of life, its spaces gently divided only by fusuma doors and shoji screens. This is not a place for socializing, but a preserved fragment of time to indulge in the luxury of solitude.",
    "about.p2": "The soft light filtering through the shoji, the subtle scent of tatami mats, and the overwhelming silence of the night. Here, taking off your watch and simply listening to the sound of your own breath will become the most precious experience of your modern journey.",
    "about.p3": "We named this inn (ryokan) \"Tokimura\"—literally translating to the \"Village of Time.\" Our wish is for this house to serve two purposes: first, to be your anchor for traveling through the immense layers of time accumulated within the town of Mikuni, Fukui. And second, to provide a space where you can listen to the sound of your own breath and the emotions that well up moment by moment, inviting you on a deep, introspective journey into the present.",
    "rooms.header.title": "Five Rooms, Five Fragments of Time",
    "rooms.header.description": "Built in 1928, this house holds five rooms, each harboring a distinct narrative. Designed in the traditional style, with spaces gently divided only by fusuma doors and shoji screens, guests share the spacious kitchen and bathroom, creating a single, peaceful dwelling together.",
    "rooms.roomA.title": "Traces of Life and the Festival’s Echo",
    "rooms.roomA.description": "The most spacious room in the house, draped in afternoon light and the faint echoes of the festival.",
    "rooms.roomB.title": "The Artisan’s Frame",
    "rooms.roomB.description": "An attic retreat where you can gaze up at the beautiful roof framing, a testament to 1928 craftsmanship.",
    "rooms.roomC.title": "The Morning Reflection",
    "rooms.roomC.description": "Serenity and morning light, waiting at the end of the corridor overlooking the courtyard garden.",
    "rooms.roomD.title": "The Crimson Shadow",
    "rooms.roomD.description": "A small, introspective room where soft light dances on traditional crimson walls.",
    "rooms.roomE.title": "The Sanctum of Shakudani Stone",
    "rooms.roomE.description": "Dignified stillness on the ground floor, facing the Shakudani stone and eternal moss garden.",
    "bicycle.title": "Tracing the Echoes: Stepping into the Living History",
    "bicycle.p1": "Once you step beyond the threshold of this 1928 house, you will hear the town’s many heartbeats. There is the noble pride of the Kitamaebune merchants, who once transformed immense wealth into a richness of spirit that still permeates these streets. There is the 13-million-year-old pulse of the earth, echoing through the stone cathedrals of Tojinbo and the sacred silence of Oshima Island. And there is the living breath of the present—the quiet focus of Zen monks and the rhythmic strikes of master craftsmen in their ancient villages.",
    "bicycle.p2": "To help you trace these echoes more profoundly and freely, we provide complimentary bicycles and carry bags for the local train. Whether riding along the coast to feel the salt in the breeze or venturing inland toward the sanctuaries of Zen, let this modest vessel be an extension of your own breath. Step out from this preserved fragment of time and immerse yourself in the living, pulsing landscape that lies before you.",
    "wealth.label": "The Depths of History and Culture",
    "wealth.title": "Wealth Transformed into Spirit.",
    "wealth.p1": "As a prominent port of call for the Kitamaebune—a massive fleet of legendary merchant ships with thousands of vessels in operation at its peak—Mikuni accumulated immense wealth. During the Edo and mid-Meiji eras, it was this northern sea route, rather than the Pacific, that served as the primary stage for Japan’s logistics and cultural dissemination.",
    "wealth.p2": "Instead of pursuing personal luxury, Mikuni's prosperous merchants invested their fortunes in building schools \"Ryushokan\", developing the harbor \"Esser Dike\", and inviting cultural figures to cultivate a richness of spirit.",
    "wealth.p3": "The elegance that still permeates the streets today, and the breathing tradition of places like the over 150-year-old \"Uoshiro\" restaurant, are the lingering fragrances of their noble aesthetic.",
    "sidelines.label": "A Remaining Miracle",
    "sidelines.title": "Saved by the Sidelines.",
    "sidelines.p_intro": "During the Meiji era, when Japan's railway network was being established, Mikuni was left out of the main logistics routes. Having escaped rapid modernization and the fires of war, its dignified streets and unhurried flow of time remain untouched today.",
    "sidelines.poem.part1": "Fukui is the hub connecting Kyoto and Kanazawa.\nBut just one hour away, there is a world the modern tracks missed.",
    "sidelines.poem.part2": "Think of this distance as a silent guardian.\nIt shielded Mikuni from the waves of development.\nIt left behind a rare, preserved fragment of history.",
    "sidelines.poem.part3": "Venture beyond the horizon.\nYour reward is a time that remains untouched.",
    "layers.label": "A Dense Accumulation",
    "layers.title": "Layers of Time, Still Breathing.",
    "layers.intro": "To breathe the air of Mikuni is to inhale the weight of centuries.\nHere, history is not a dusty textbook;\nit is a living, pulsing landscape that lies before you.\nWithin just a few minutes of walking,\nyou can journey across millions of years.",
    "layers.item1.title": "13 Million Years Ago: Nature’s Cathedral",
    "layers.item1.description": "The story begins with the earth’s ancient memory. The rugged cliffs of Tojinbo and the sacred, uninhabited island of Oshima were forged by volcanic fury 13 million years ago. These majestic columnar formations rise like a magnificent cathedral of stone, where the eternal forces of nature speak in deep, echoing tones.",
    "layers.item2.title": "1375: Medieval Stillness",
    "layers.item2.description": "As you step into the town, time shifts to the Middle Ages. At Takidanji Temple, the oldest in Mikuni, moss has quietly accumulated for over 650 years, absorbing the light and the silence. Every step along its ancient stone path invites you to dissolve into medieval tranquility, far removed from the present world.",
    "layers.item3.title": "1541: The Unquenchable Passion",
    "layers.item3.description": "Behind the silence, a fire of devotion burns. Since 1541, Mikuni Shrine has stood as the guardian of the town’s spirit. This prayer culminates in the Mikuni Festival, a 300-year-old tradition where giant warrior floats—reaching 6.5 meters in height—shake the historic streets. It is the lifeblood of Mikuni, pulsing with a passion that never fades.",
    "layers.item4.title": "1873: Echoes of Elegance",
    "layers.item4.description": "With the dawn of the modern era, Mikuni flourished as a cultural gateway. Uoshiro, founded in 1873, was once a renowned stage for social and cultural exchange in the historic district. Today, within its walls that still house the memories of that era, a Kyoto-trained master prepares local delicacies, blending the town’s rich history with its vibrant present.",
    "layers.item5.title": "1882: The Horizon’s Curve",
    "layers.item5.description": "In 1882, a Dutch engineer named Esser reshaped the coast with a visionary brick breakwater. The Esser Dike remains a monument to Meiji-era ingenuity, its beautiful curve protecting the harbor for over a century. When its silhouette is painted in the vivid colors of the sunset, you feel the quiet harmony between human engineering and the vast Sea of Japan.",
    "layers.conclusion": "When you wake in Tokimura (built in 1928),\nyou will realize that you are more than a visitor.\nYou are the latest line being written in the continuous,\nbreathing story of this town.",
    "guide.local.label": "Local Guidebook",
    "guide.local.title": "A Detailed Local Guide: 4 Days in Historic Mikuni",
    "guide.local.description": "A recommended route by the host for tracing the layers of history with your own feet.",
    "guide.transition": "Immersed in Mikuni's profound history,\nyou will naturally yearn to discover stories that lie further beyond...",
    "anchor.label": "Mikuni as Your Hub",
    "anchor.title": "The Anchor of Your Fukui Journey.",
    "anchor.intro": "If you wish to touch the depths of Fukui, your basecamp must be by the sea. By making this \"preserved fragment\" your home for 3 or 4 nights, your excursions into Fukui become an extension of Mikuni’s stillness. Let the rhythmic tides of this port town be the anchor for your journeys to Zen sanctuaries and master craft villages beyond.",
    "anchor.p1": "A day trip inland to explore Eiheiji Temple (Zen) or the villages of Echizen Washi paper and forged cutlery (Craftsmanship) will be filled with pleasant stimulation. Yet, the place you should return to at the end of your journey is the tranquility of Mikuni, where the sound of the waves, hot springs, and rich culinary delights await.",
    "anchor.p2": "By dropping your \"anchor\" in Mikuni for three or four nights, you cease to be a mere tourist and become a part of the deep spirituality of this land.",
    "guide.trips.label": "Day Trips Guidebook",
    "guide.trips.title": "Beyond the Port: Zen and Craftsmanship Day Trips",
    "guide.trips.description": "A guide to exploring the abyss of Fukui (Eiheiji and Craft villages) in a single day, using Mikuni as your anchor.",
    "access.label": "Journey to the Coast",
    "access.title": "Access",
    "access.kyoto.title": "From Kyoto",
    "access.kyoto.time": "(Approx. 2.5 hours)",
    "access.kyoto.description": "Take the Limited Express \"Thunderbird\" to JR Fukui Station. Transfer to the Echizen Railway (Mikuni-Awara Line) and disembark at Mikuni Station. *Note: Be careful not to confuse this with the final stop, \"Mikuni-Minato Station.\" The house is a 10-minute walk away. I highly recommend a route through the atmospheric old streets of the Kitamaebune era.",
    "access.kanazawa.title": "From Kanazawa",
    "access.kanazawa.time": "(Approx. 1h 30m)",
    "access.kanazawa.description": "Take the JR local train or Shinkansen to JR Awaraonsen Station. Board the Keifuku Bus (Route 85 or 97) and alight at Eishoji (Tatemachi), a stop in the heart of the historic district. This cost-effective and scenic route offers a slower transition from the city’s pace to our quiet harbor.",
    "access.takayama.title": "From Takayama",
    "access.takayama.time": "(Approx. 3.5 – 4 hours)",
    "access.takayama.description": "Take an express bus (Nohi Bus) from Takayama to Kanazawa Station. From Kanazawa, follow the coastal route via JR Awaraonsen Station as described above. This \"Mountains to Sea\" route connects Japan’s mountainous heart to its historic coastal gateway.",
    "contact.label": "Inquiries",
    "contact.title": "Contact Tokimura",
    "contact.airbnb_notice": "We welcome guests who understand the value of this place and love silence. All reservations are accepted via Airbnb.",
    "contact.form.title": "Send an Inquiry",
    "contact.form.name": "Name",
    "contact.form.email": "Email",
    "contact.form.message": "Message",
    "contact.form.send": "Send",
    "contact.form.captcha_disclosure": "This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.",
    "contact.success_msg": "Message Sent successfully.",
    "footer.brand": "Tokimura",
    "footer.location": "Mikuni, Fukui, Japan",
    "footer.copyright": "Tokimura. All rights reserved.",
    "alt.hero.main_image": "Authentic traditional Japanese ryokan exterior at dusk, quiet and uncrowded, inviting solitude.",
    "alt.about.slider_main": "Serene traditional Japanese ryokan interior, showcasing authentic wabi-sabi aesthetics and quiet beauty.",
    "alt.about.slider_sub1": "Introspective detail of a traditional Japanese ryokan room, emphasizing quiet solitude and authentic design.",
    "alt.about.slider_sub2": "Beautiful quiet garden view from a traditional Japanese ryokan, offering a serene natural escape.",
    "alt.about.video1_poster": "Poster: Serene garden view, reflecting the quiet nature and authentic beauty of this traditional Japanese ryokan.",
    "alt.about.video2_poster": "Poster: Peaceful moss and water in a traditional Japanese garden, evoking quiet contemplation and natural beauty.",
    "alt.rooms.roomA": "Spacious traditional Japanese ryokan room, filled with natural light and a sense of history, perfect for quiet reflection.",
    "alt.rooms.roomB": "Authentic traditional Japanese ryokan attic room, showcasing beautiful old craftsmanship and a quiet, introspective atmosphere.",
    "alt.rooms.roomC": "Serene traditional Japanese ryokan corridor with morning light, offering quiet views of a beautiful garden.",
    "alt.rooms.roomD": "Introspective traditional Japanese ryokan room with soft light on crimson walls, ideal for solitude and quiet contemplation.",
    "alt.rooms.roomE": "Quiet traditional Japanese ryokan room facing a serene Shakudani stone garden, embodying wabi-sabi and timeless beauty.",
    "alt.bicycle.main": "Complimentary rental bicycle for exploring the authentic, uncrowded nature and history of this beautiful Japanese region.",
    "alt.wealth.s1_main": "Authentic traditional Japanese pottery, reflecting the rich history and craftsmanship of this unspoiled region.",
    "alt.wealth.s1_sub1": "Beautiful ceramic art, a testament to the authentic and quiet artistic traditions of Japan.",
    "alt.wealth.s1_sub2": "Uncrowded historic street in a traditional Japanese town, preserving the quiet beauty and authentic atmosphere of old Japan.",
    "alt.wealth.s2_main": "Authentic traditional Japanese pottery, reflecting the rich history and craftsmanship of this unspoiled region.",
    "alt.wealth.s2_sub1": "Historic Japanese elementary school building, a beautiful and authentic architectural fragment of local history.",
    "alt.wealth.s2_sub2": "Beautiful and quiet Escher Dike pier, a historical landmark connecting nature and human ingenuity in Japan.",
    "alt.sidelines.s1_main": "Unspoiled traditional Japanese townscape, a beautiful and quiet fragment of history untouched by crowds.",
    "alt.sidelines.s1_sub1": "Introspective shadows on a traditional Japanese street, evoking a sense of quiet time and authentic history.",
    "alt.sidelines.s1_sub2": "Serene moss garden, a beautiful example of wabi-sabi and quiet nature in an authentic Japanese setting.",
    "alt.sidelines.s2_main": "Beautiful and quiet Japanese nature, an unspoiled landscape offering solitude and a connection to authentic time.",
    "alt.sidelines.s2_sub1": "Serene sea horizon, a quiet and beautiful natural view from an uncrowded Japanese coast.",
    "alt.sidelines.s2_sub2": "Vast and beautiful sky over an unspoiled Japanese landscape, inviting quiet contemplation.",
    "alt.sidelines.s3_main": "Authentic traditional Japanese townscape with a view of nature, a quiet and beautiful place untouched by crowds.",
    "alt.sidelines.s3_sub1": "Quiet and beautiful sea horizon from an uncrowded Japanese port town, offering serene views.",
    "alt.sidelines.s3_sub2": "Expansive sky over a beautiful and authentic Japanese coastal town, perfect for quiet reflection.",
    "alt.sidelines.s4_main": "Beautiful and authentic traditional Japanese architecture in a quiet, uncrowded setting, rich in history.",
    "alt.sidelines.s4_sub1": "Serene sea horizon from a historic Japanese port, a beautiful and quiet view for solitude.",
    "alt.sidelines.s4_sub2": "Clear sky over a beautiful and authentic Japanese town, inviting quiet contemplation and a sense of timelessness.",
    "alt.layers.item1_main": "Majestic Tojinbo cliffs, a natural cathedral of stone, showcasing the raw beauty and ancient history of Japan's unspoiled nature.",
    "alt.layers.item1_sub1": "Dramatic columnar jointing of Tojinbo, a unique natural wonder and a quiet, uncrowded geological marvel in Japan.",
    "alt.layers.item1_sub2": "Sacred Oshima Island, a beautiful and quiet natural sanctuary off the uncrowded Japanese coast, rich in history.",
    "alt.layers.item2_main": "Serene Takidanji Temple, an authentic and quiet medieval Japanese temple with ancient moss gardens, perfect for introspection.",
    "alt.layers.item2_sub1": "Introspective detail of moss and stone at Takidanji Temple, embodying wabi-sabi and the quiet passage of time in Japan.",
    "alt.layers.item2_sub2": "Beautiful and quiet ancient stone path at Takidanji Temple, inviting solitude and a connection to Japan's deep history.",
    "alt.layers.item3_main": "Vibrant Mikuni Festival float, a powerful expression of authentic Japanese tradition and local history, in an uncrowded setting.",
    "alt.layers.item3_sub1": "Traditional Mikuni Shrine architecture, a beautiful and authentic guardian of local history and spiritual life in Japan.",
    "alt.layers.item3_sub2": "Dynamic scene from the Mikuni Festival, showcasing authentic Japanese culture and the living history of this unspoiled town.",
    "alt.layers.item4_main": "Historic Uoshiro restaurant interior, reflecting the elegant past and authentic culinary traditions of a quiet Japanese port town.",
    "alt.layers.item4_sub1": "Introspective detail of traditional Japanese interior design at Uoshiro, embodying wabi-sabi and quiet elegance.",
    "alt.layers.item4_sub2": "Authentic traditional Japanese dining experience at Uoshiro, a beautiful and quiet place to savor local history.",
    "alt.layers.item5_main": "Beautiful curve of the historic Esser Dike pier at sunset, a quiet and unspoiled landmark connecting human history with nature in Japan.",
    "alt.layers.item5_sub1": "Introspective detail of the historic Esser Dike, showcasing the enduring craftsmanship and quiet beauty of this Japanese coastal landmark.",
    "alt.layers.item5_sub2": "Serene view of the Esser Dike pier extending into the uncrowded Sea of Japan, a beautiful and quiet place for solitude.",
    "alt.anchor.main": "Beautiful and quiet Sea of Japan coast, an unspoiled natural landscape perfect for introspection and solo travel.",
    "alt.anchor.sub1": "Authentic Japanese craftsmanship in a quiet village, showcasing traditional skills and a deep connection to history.",
    "alt.anchor.sub2": "Serene traditional Japanese hot spring (onsen), offering quiet relaxation and a beautiful natural experience.",
    "alt.access.train": "Scenic Echizen Railway train traveling through beautiful, uncrowded Japanese countryside, a quiet journey through nature."
  }
};

export default ui;